### ISSUE TITLE
toil-rnaseq: toil worker cannot find download_sample

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/cgl-docker-lib#123]
`toil-rnaseq run aws:us-west-2:jeltje-jobstore-bucket --batchSystem=mesos --mesosMaster mesos-master:5050 --manifest toil-rnaseq-manifest.tsv`

Dies with many repetitions of

```
WARNING:toil.leader:e349cc50-91b4-4114-9118-7c90bb32667b:       ---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:e349cc50-91b4-4114-9118-7c90bb32667b:       Traceback (most recent call last):
WARNING:toil.leader:e349cc50-91b4-4114-9118-7c90bb32667b:         File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 273, in main
WARNING:toil.leader:e349cc50-91b4-4114-9118-7c90bb32667b:           fileStore=fileStore)
WARNING:toil.leader:e349cc50-91b4-4114-9118-7c90bb32667b:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1294, in _execute
WARNING:toil.leader:e349cc50-91b4-4114-9118-7c90bb32667b:           returnValues = self.run(fileStore)
WARNING:toil.leader:e349cc50-91b4-4114-9118-7c90bb32667b:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1398, in run
WARNING:toil.leader:e349cc50-91b4-4114-9118-7c90bb32667b:           userFunction = self._getUserFunction()
WARNING:toil.leader:e349cc50-91b4-4114-9118-7c90bb32667b:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1374, in _getUserFunction
WARNING:toil.leader:e349cc50-91b4-4114-9118-7c90bb32667b:           return getattr(userFunctionModule, self.userFunctionName)
WARNING:toil.leader:e349cc50-91b4-4114-9118-7c90bb32667b:       AttributeError: 'module' object has no attribute 'download_sample'
WARNING:toil.leader:e349cc50-91b4-4114-9118-7c90bb32667b:       Exiting the worker because of a failed jobWrapper on host ip-172-31-33-13
WARNING:toil.leader:e349cc50-91b4-4114-9118-7c90bb32667b:       ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-33-13

```

**Comment by Jeltje** [comment]
Running locally:
`toil-rnaseq run ./test-jobstore --manifest small.manifest`
dies, see
http://hgwdev.cse.ucsc.edu/~jeltje/toil/local.log

**Comment by jvivian** [comment]
The HGWDEV log was very useful.  Changes just went through this morning that will have fixed the error you ran into running it locally, which I'm _hoping_ is what is causing the vague error when running with mesos.

**Comment by jvivian** [comment]
@Jeltje If you get a chance, `pip install --upgrade --pre toil-scripts` will have addressed your 2nd error and possibly your first.

**Comment by jvivian** [comment]
See  BD2KGenomics/toil-scripts#291 .   Toil-scripts needs to be on every leader/worker otherwise you'll get this error.  Once I do BD2KGenomics/cgcloud#176 this won't be an issue.
