### ISSUE TITLE
RNA seq cgl wrapper gives incorrect error message 

### ISSUE THREAD

**Issue by nsjake** [BD2KGenomics/cgl-docker-lib#165]
command:

```
docker run \
    -v /mnt/jobstore:/mnt/jobstore \
    -v /var/run/docker.sock:/var/run/docker.sock \
    quay.io/ucsc_cgl/rnaseq-cgl-pipeline \
    --star=mnt/test-inputs/starIndex_hg38_no_alt.tar.gz \
    --rsem=/mnt/test-inputs/rsem_ref_hg38_no_alt.tar.gz \
    --kallisto=/mnt/test-inputs/kallisto_hg38.idx \
    --samples=/mnt/test-inputs/single-sample.tar
```

error message:

```
Traceback (most recent call last):
  File "/opt/rnaseq-pipeline/wrapper.py", line 102, in <module>
    main()
  File "/opt/rnaseq-pipeline/wrapper.py", line 93, in main
    "'/full/path/to/sample1.tar'. You  provided {}.".format(args.samples))
__main__.IllegalArgumentException: Sample inputs must point to a file's full path, e.g. '/full/path/to/sample1.tar'. You  provided ['/mnt/test-inputs/single-sample.tar'].
```

Notice that the `sample input` path is correct, but that the `star` path is invalid.

**Comment by jvivian** [comment]
Error not from the 2.0.x container branch.
